# Generated by Django 3.1 on 2024-06-01 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caterogy_name', models.CharField(max_length=250, unique=True)),
                ('slug', models.SlugField(max_length=500, unique=True)),
                ('discription', models.TextField()),
                ('cat_image', models.ImageField(blank=True, upload_to='media/category/')),
            ],
        ),
    ]
