# Generated by Django 3.1 on 2024-05-29 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_variations'),
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart_items',
            name='variation',
            field=models.ManyToManyField(blank=True, to='store.variations'),
        ),
    ]
